Ext.define('Airtelmdm.airtelmdm.shared.mdm.model.masterdatamanagment.PtopSearchModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "itemid",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "itemcode",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "itemdescription",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "partnumber",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "partdescription",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "model",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "itemtypeid",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "itemtypename",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "itemsubtypeid",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "itemsubtypename",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "itemmaintypeid",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "itemmaintypename",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "itemcategoryid",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "itemcategoryname",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "technologyid",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "technologyname",
          "type": "string",
          "defaultValue": ""
     }]
});