Ext.define('Airtelmdm.airtelmdm.shared.mdm.model.masterdatamanagment.mdmdomain.SpocrequestModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "spocrequestid",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "userid",
          "reference": "User",
          "defaultValue": ""
     }, {
          "name": "partnumber",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "partdescription",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "itmmainid",
          "reference": "Itemmaintype",
          "defaultValue": ""
     }, {
          "name": "itemsubid",
          "reference": "Itemsubtype",
          "defaultValue": ""
     }, {
          "name": "manufacturerid",
          "reference": "Manufacturer",
          "defaultValue": ""
     }, {
          "name": "uomid",
          "reference": "Uom",
          "defaultValue": ""
     }, {
          "name": "itemcategoryid",
          "reference": "Itemcategorytype",
          "defaultValue": ""
     }, {
          "name": "itemtypeid",
          "reference": "Itemtype",
          "defaultValue": ""
     }, {
          "name": "sbpid",
          "reference": "Sbp",
          "defaultValue": ""
     }, {
          "name": "statusid",
          "reference": "Spocrequeststatus",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});